---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: poe-tracker
spec:
  encryptedData:
    .dockerconfigjson: AgC29jvsRok/Lx2syZuJHSQEj2W25uZjmEqpxpH1z/6esViOhA7K8svbWttpnWcY5YHFuZyAAf+wgIAkTZAysqGf+Mz3Ywwtb2JKVf2Y5D+9ZEyu+P/x1IEMHEi91xAYLajqPwvYHKfgINeUlBWcovoOuPj5pMvm/YwOSxwodTegoZk7R+p3H8+IRKyycMvSBausJw566cJSnZDhP7pjhwWXJOBxFnBIIbkG0hwiaFvWte15xpqTgH5jZMYxL3tCmuXTNDBbU3i6scamIKBQ2VckdI0i1xfzc25klPgDPzqpv+7PASQhUWTtZ4vKZYrN6BrbudxGl5aoPDg8nCFZkKkYSfVgxN1kF62bMQDLUKoNbJWBzfQrpsbAdLHiQzQgW5frjoToNQeELWNe17JbgtRfh1xKhddsrQp065/4bGiatY5w8sH8ExdaZZHSOfaacKCty6HVm/Fro+gWYEi1iOg4ILh3Am5I9cOuKEdLnBHaAc795OUe/G5HdcVebAHbMknx7zcKZdUoIGThBos+w2EPn3S8wTsHa7PCdXYjdYgIpulEnhpaOXPyVVeSEOXAN9N+xaWUnoVPXfsWX45vlZLAaC1BogrsMzYlcJzCjpE2PGdGfknz1i1iwgjq0OrHnBjCcc9FoC6KUE8hy8PRcHsdHVXjmwnB8yKqGxFs2a9d5kp7MLR3RCQncUmnpiRVpRLKoU9yGTmKgWKGsSUTIwYBqJSc4+PLMnC6/NX1j9XEfl9vtd1g3dpH1khEWV6jOY59LEyshm6G9Muej6k2N/ynCaUuA1UP/rxtTSW+q0/u1tw49N3mjZ1ifDne/r1M2gGkamSbW4jU2V60TK/aN789uCmV/K8OCeRd87uKCF/BcrCvhzsbApu01hYbJl72qXmeINrmV7vO1uTqKiGEBfjXH+XY5LotA26tsLX/uGK74iU=
  template:
    metadata:
      name: ghcr-pull
      namespace: poe-tracker
    type: kubernetes.io/dockerconfigjson
