apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vtgate.serviceName }}
  labels:
    {{- include "poe-tracker.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ required "vtgate.externalName is required" .Values.vtgate.externalName }}
