// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: exchange/v1/admin.proto

package exchangev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPlaceholderCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaceholderCurrenciesRequest) Reset() {
	*x = ListPlaceholderCurrenciesRequest{}
	mi := &file_exchange_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaceholderCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaceholderCurrenciesRequest) ProtoMessage() {}

func (x *ListPlaceholderCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaceholderCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListPlaceholderCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{0}
}

type PlaceholderCurrency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyId    int64                  `protobuf:"varint,1,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	ItemPath      string                 `protobuf:"bytes,2,opt,name=item_path,json=itemPath,proto3" json:"item_path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DiscoveredAt  int64                  `protobuf:"varint,4,opt,name=discovered_at,json=discoveredAt,proto3" json:"discovered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderCurrency) Reset() {
	*x = PlaceholderCurrency{}
	mi := &file_exchange_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderCurrency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderCurrency) ProtoMessage() {}

func (x *PlaceholderCurrency) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderCurrency.ProtoReflect.Descriptor instead.
func (*PlaceholderCurrency) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceholderCurrency) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *PlaceholderCurrency) GetItemPath() string {
	if x != nil {
		return x.ItemPath
	}
	return ""
}

func (x *PlaceholderCurrency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaceholderCurrency) GetDiscoveredAt() int64 {
	if x != nil {
		return x.DiscoveredAt
	}
	return 0
}

type ListPlaceholderCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*PlaceholderCurrency `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlaceholderCurrenciesResponse) Reset() {
	*x = ListPlaceholderCurrenciesResponse{}
	mi := &file_exchange_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlaceholderCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlaceholderCurrenciesResponse) ProtoMessage() {}

func (x *ListPlaceholderCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlaceholderCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListPlaceholderCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListPlaceholderCurrenciesResponse) GetCurrencies() []*PlaceholderCurrency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type CurateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemPath      string                 `protobuf:"bytes,1,opt,name=item_path,json=itemPath,proto3" json:"item_path,omitempty"`
	TradeId       string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	EmojiId       string                 `protobuf:"bytes,4,opt,name=emoji_id,json=emojiId,proto3" json:"emoji_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurateCurrencyRequest) Reset() {
	*x = CurateCurrencyRequest{}
	mi := &file_exchange_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurateCurrencyRequest) ProtoMessage() {}

func (x *CurateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CurateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CurateCurrencyRequest) GetItemPath() string {
	if x != nil {
		return x.ItemPath
	}
	return ""
}

func (x *CurateCurrencyRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *CurateCurrencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurateCurrencyRequest) GetEmojiId() string {
	if x != nil {
		return x.EmojiId
	}
	return ""
}

type CurateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurateCurrencyResponse) Reset() {
	*x = CurateCurrencyResponse{}
	mi := &file_exchange_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurateCurrencyResponse) ProtoMessage() {}

func (x *CurateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*CurateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{4}
}

type SyncCurrenciesFromScoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Realm         string                 `protobuf:"bytes,1,opt,name=realm,proto3" json:"realm,omitempty"`
	League        string                 `protobuf:"bytes,2,opt,name=league,proto3" json:"league,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCurrenciesFromScoutRequest) Reset() {
	*x = SyncCurrenciesFromScoutRequest{}
	mi := &file_exchange_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCurrenciesFromScoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCurrenciesFromScoutRequest) ProtoMessage() {}

func (x *SyncCurrenciesFromScoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCurrenciesFromScoutRequest.ProtoReflect.Descriptor instead.
func (*SyncCurrenciesFromScoutRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *SyncCurrenciesFromScoutRequest) GetRealm() string {
	if x != nil {
		return x.Realm
	}
	return ""
}

func (x *SyncCurrenciesFromScoutRequest) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

type SyncCurrenciesFromScoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,2,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCurrenciesFromScoutResponse) Reset() {
	*x = SyncCurrenciesFromScoutResponse{}
	mi := &file_exchange_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCurrenciesFromScoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCurrenciesFromScoutResponse) ProtoMessage() {}

func (x *SyncCurrenciesFromScoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCurrenciesFromScoutResponse.ProtoReflect.Descriptor instead.
func (*SyncCurrenciesFromScoutResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *SyncCurrenciesFromScoutResponse) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncCurrenciesFromScoutResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

type BootstrapDefaultRatePairsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseItemPath   string                 `protobuf:"bytes,1,opt,name=base_item_path,json=baseItemPath,proto3" json:"base_item_path,omitempty"`
	QuoteItemPaths []string               `protobuf:"bytes,2,rep,name=quote_item_paths,json=quoteItemPaths,proto3" json:"quote_item_paths,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BootstrapDefaultRatePairsRequest) Reset() {
	*x = BootstrapDefaultRatePairsRequest{}
	mi := &file_exchange_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapDefaultRatePairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapDefaultRatePairsRequest) ProtoMessage() {}

func (x *BootstrapDefaultRatePairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapDefaultRatePairsRequest.ProtoReflect.Descriptor instead.
func (*BootstrapDefaultRatePairsRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *BootstrapDefaultRatePairsRequest) GetBaseItemPath() string {
	if x != nil {
		return x.BaseItemPath
	}
	return ""
}

func (x *BootstrapDefaultRatePairsRequest) GetQuoteItemPaths() []string {
	if x != nil {
		return x.QuoteItemPaths
	}
	return nil
}

type BootstrapDefaultRatePairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*DefaultRatePair     `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapDefaultRatePairsResponse) Reset() {
	*x = BootstrapDefaultRatePairsResponse{}
	mi := &file_exchange_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapDefaultRatePairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapDefaultRatePairsResponse) ProtoMessage() {}

func (x *BootstrapDefaultRatePairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapDefaultRatePairsResponse.ProtoReflect.Descriptor instead.
func (*BootstrapDefaultRatePairsResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *BootstrapDefaultRatePairsResponse) GetPairs() []*DefaultRatePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

var File_exchange_v1_admin_proto protoreflect.FileDescriptor

const file_exchange_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x17exchange/v1/admin.proto\x12\vexchange.v1\x1a\x17exchange/v1/query.proto\"\"\n" +
	" ListPlaceholderCurrenciesRequest\"\x8c\x01\n" +
	"\x13PlaceholderCurrency\x12\x1f\n" +
	"\vcurrency_id\x18\x01 \x01(\x03R\n" +
	"currencyId\x12\x1b\n" +
	"\titem_path\x18\x02 \x01(\tR\bitemPath\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rdiscovered_at\x18\x04 \x01(\x03R\fdiscoveredAt\"e\n" +
	"!ListPlaceholderCurrenciesResponse\x12@\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2 .exchange.v1.PlaceholderCurrencyR\n" +
	"currencies\"~\n" +
	"\x15CurateCurrencyRequest\x12\x1b\n" +
	"\titem_path\x18\x01 \x01(\tR\bitemPath\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bemoji_id\x18\x04 \x01(\tR\aemojiId\"\x18\n" +
	"\x16CurateCurrencyResponse\"N\n" +
	"\x1eSyncCurrenciesFromScoutRequest\x12\x14\n" +
	"\x05realm\x18\x01 \x01(\tR\x05realm\x12\x16\n" +
	"\x06league\x18\x02 \x01(\tR\x06league\"i\n" +
	"\x1fSyncCurrenciesFromScoutResponse\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12#\n" +
	"\rskipped_count\x18\x02 \x01(\x05R\fskippedCount\"r\n" +
	" BootstrapDefaultRatePairsRequest\x12$\n" +
	"\x0ebase_item_path\x18\x01 \x01(\tR\fbaseItemPath\x12(\n" +
	"\x10quote_item_paths\x18\x02 \x03(\tR\x0equoteItemPaths\"W\n" +
	"!BootstrapDefaultRatePairsResponse\x122\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1c.exchange.v1.DefaultRatePairR\x05pairs2\xdf\x03\n" +
	"\x14ExchangeAdminService\x12z\n" +
	"\x19ListPlaceholderCurrencies\x12-.exchange.v1.ListPlaceholderCurrenciesRequest\x1a..exchange.v1.ListPlaceholderCurrenciesResponse\x12Y\n" +
	"\x0eCurateCurrency\x12\".exchange.v1.CurateCurrencyRequest\x1a#.exchange.v1.CurateCurrencyResponse\x12t\n" +
	"\x17SyncCurrenciesFromScout\x12+.exchange.v1.SyncCurrenciesFromScoutRequest\x1a,.exchange.v1.SyncCurrenciesFromScoutResponse\x12z\n" +
	"\x19BootstrapDefaultRatePairs\x12-.exchange.v1.BootstrapDefaultRatePairsRequest\x1a..exchange.v1.BootstrapDefaultRatePairsResponseBFZDgithub.com/grysha11/poe-tg-tracker/internal/pb/exchangev1;exchangev1b\x06proto3"

var (
	file_exchange_v1_admin_proto_rawDescOnce sync.Once
	file_exchange_v1_admin_proto_rawDescData []byte
)

func file_exchange_v1_admin_proto_rawDescGZIP() []byte {
	file_exchange_v1_admin_proto_rawDescOnce.Do(func() {
		file_exchange_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_v1_admin_proto_rawDesc), len(file_exchange_v1_admin_proto_rawDesc)))
	})
	return file_exchange_v1_admin_proto_rawDescData
}

var file_exchange_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_exchange_v1_admin_proto_goTypes = []any{
	(*ListPlaceholderCurrenciesRequest)(nil),  // 0: exchange.v1.ListPlaceholderCurrenciesRequest
	(*PlaceholderCurrency)(nil),               // 1: exchange.v1.PlaceholderCurrency
	(*ListPlaceholderCurrenciesResponse)(nil), // 2: exchange.v1.ListPlaceholderCurrenciesResponse
	(*CurateCurrencyRequest)(nil),             // 3: exchange.v1.CurateCurrencyRequest
	(*CurateCurrencyResponse)(nil),            // 4: exchange.v1.CurateCurrencyResponse
	(*SyncCurrenciesFromScoutRequest)(nil),    // 5: exchange.v1.SyncCurrenciesFromScoutRequest
	(*SyncCurrenciesFromScoutResponse)(nil),   // 6: exchange.v1.SyncCurrenciesFromScoutResponse
	(*BootstrapDefaultRatePairsRequest)(nil),  // 7: exchange.v1.BootstrapDefaultRatePairsRequest
	(*BootstrapDefaultRatePairsResponse)(nil), // 8: exchange.v1.BootstrapDefaultRatePairsResponse
	(*DefaultRatePair)(nil),                   // 9: exchange.v1.DefaultRatePair
}
var file_exchange_v1_admin_proto_depIdxs = []int32{
	1, // 0: exchange.v1.ListPlaceholderCurrenciesResponse.currencies:type_name -> exchange.v1.PlaceholderCurrency
	9, // 1: exchange.v1.BootstrapDefaultRatePairsResponse.pairs:type_name -> exchange.v1.DefaultRatePair
	0, // 2: exchange.v1.ExchangeAdminService.ListPlaceholderCurrencies:input_type -> exchange.v1.ListPlaceholderCurrenciesRequest
	3, // 3: exchange.v1.ExchangeAdminService.CurateCurrency:input_type -> exchange.v1.CurateCurrencyRequest
	5, // 4: exchange.v1.ExchangeAdminService.SyncCurrenciesFromScout:input_type -> exchange.v1.SyncCurrenciesFromScoutRequest
	7, // 5: exchange.v1.ExchangeAdminService.BootstrapDefaultRatePairs:input_type -> exchange.v1.BootstrapDefaultRatePairsRequest
	2, // 6: exchange.v1.ExchangeAdminService.ListPlaceholderCurrencies:output_type -> exchange.v1.ListPlaceholderCurrenciesResponse
	4, // 7: exchange.v1.ExchangeAdminService.CurateCurrency:output_type -> exchange.v1.CurateCurrencyResponse
	6, // 8: exchange.v1.ExchangeAdminService.SyncCurrenciesFromScout:output_type -> exchange.v1.SyncCurrenciesFromScoutResponse
	8, // 9: exchange.v1.ExchangeAdminService.BootstrapDefaultRatePairs:output_type -> exchange.v1.BootstrapDefaultRatePairsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exchange_v1_admin_proto_init() }
func file_exchange_v1_admin_proto_init() {
	if File_exchange_v1_admin_proto != nil {
		return
	}
	file_exchange_v1_query_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_v1_admin_proto_rawDesc), len(file_exchange_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_v1_admin_proto_goTypes,
		DependencyIndexes: file_exchange_v1_admin_proto_depIdxs,
		MessageInfos:      file_exchange_v1_admin_proto_msgTypes,
	}.Build()
	File_exchange_v1_admin_proto = out.File
	file_exchange_v1_admin_proto_goTypes = nil
	file_exchange_v1_admin_proto_depIdxs = nil
}
