// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: exchange/v1/admin.proto

package exchangev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeAdminService_ListPlaceholderCurrencies_FullMethodName = "/exchange.v1.ExchangeAdminService/ListPlaceholderCurrencies"
	ExchangeAdminService_CurateCurrency_FullMethodName            = "/exchange.v1.ExchangeAdminService/CurateCurrency"
	ExchangeAdminService_SyncCurrenciesFromScout_FullMethodName   = "/exchange.v1.ExchangeAdminService/SyncCurrenciesFromScout"
	ExchangeAdminService_BootstrapDefaultRatePairs_FullMethodName = "/exchange.v1.ExchangeAdminService/BootstrapDefaultRatePairs"
)

// ExchangeAdminServiceClient is the client API for ExchangeAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeAdminServiceClient interface {
	ListPlaceholderCurrencies(ctx context.Context, in *ListPlaceholderCurrenciesRequest, opts ...grpc.CallOption) (*ListPlaceholderCurrenciesResponse, error)
	CurateCurrency(ctx context.Context, in *CurateCurrencyRequest, opts ...grpc.CallOption) (*CurateCurrencyResponse, error)
	SyncCurrenciesFromScout(ctx context.Context, in *SyncCurrenciesFromScoutRequest, opts ...grpc.CallOption) (*SyncCurrenciesFromScoutResponse, error)
	BootstrapDefaultRatePairs(ctx context.Context, in *BootstrapDefaultRatePairsRequest, opts ...grpc.CallOption) (*BootstrapDefaultRatePairsResponse, error)
}

type exchangeAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeAdminServiceClient(cc grpc.ClientConnInterface) ExchangeAdminServiceClient {
	return &exchangeAdminServiceClient{cc}
}

func (c *exchangeAdminServiceClient) ListPlaceholderCurrencies(ctx context.Context, in *ListPlaceholderCurrenciesRequest, opts ...grpc.CallOption) (*ListPlaceholderCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlaceholderCurrenciesResponse)
	err := c.cc.Invoke(ctx, ExchangeAdminService_ListPlaceholderCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeAdminServiceClient) CurateCurrency(ctx context.Context, in *CurateCurrencyRequest, opts ...grpc.CallOption) (*CurateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurateCurrencyResponse)
	err := c.cc.Invoke(ctx, ExchangeAdminService_CurateCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeAdminServiceClient) SyncCurrenciesFromScout(ctx context.Context, in *SyncCurrenciesFromScoutRequest, opts ...grpc.CallOption) (*SyncCurrenciesFromScoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncCurrenciesFromScoutResponse)
	err := c.cc.Invoke(ctx, ExchangeAdminService_SyncCurrenciesFromScout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeAdminServiceClient) BootstrapDefaultRatePairs(ctx context.Context, in *BootstrapDefaultRatePairsRequest, opts ...grpc.CallOption) (*BootstrapDefaultRatePairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapDefaultRatePairsResponse)
	err := c.cc.Invoke(ctx, ExchangeAdminService_BootstrapDefaultRatePairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeAdminServiceServer is the server API for ExchangeAdminService service.
// All implementations must embed UnimplementedExchangeAdminServiceServer
// for forward compatibility.
type ExchangeAdminServiceServer interface {
	ListPlaceholderCurrencies(context.Context, *ListPlaceholderCurrenciesRequest) (*ListPlaceholderCurrenciesResponse, error)
	CurateCurrency(context.Context, *CurateCurrencyRequest) (*CurateCurrencyResponse, error)
	SyncCurrenciesFromScout(context.Context, *SyncCurrenciesFromScoutRequest) (*SyncCurrenciesFromScoutResponse, error)
	BootstrapDefaultRatePairs(context.Context, *BootstrapDefaultRatePairsRequest) (*BootstrapDefaultRatePairsResponse, error)
	mustEmbedUnimplementedExchangeAdminServiceServer()
}

// UnimplementedExchangeAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeAdminServiceServer struct{}

func (UnimplementedExchangeAdminServiceServer) ListPlaceholderCurrencies(context.Context, *ListPlaceholderCurrenciesRequest) (*ListPlaceholderCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlaceholderCurrencies not implemented")
}
func (UnimplementedExchangeAdminServiceServer) CurateCurrency(context.Context, *CurateCurrencyRequest) (*CurateCurrencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CurateCurrency not implemented")
}
func (UnimplementedExchangeAdminServiceServer) SyncCurrenciesFromScout(context.Context, *SyncCurrenciesFromScoutRequest) (*SyncCurrenciesFromScoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncCurrenciesFromScout not implemented")
}
func (UnimplementedExchangeAdminServiceServer) BootstrapDefaultRatePairs(context.Context, *BootstrapDefaultRatePairsRequest) (*BootstrapDefaultRatePairsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BootstrapDefaultRatePairs not implemented")
}
func (UnimplementedExchangeAdminServiceServer) mustEmbedUnimplementedExchangeAdminServiceServer() {}
func (UnimplementedExchangeAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeExchangeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeAdminServiceServer will
// result in compilation errors.
type UnsafeExchangeAdminServiceServer interface {
	mustEmbedUnimplementedExchangeAdminServiceServer()
}

func RegisterExchangeAdminServiceServer(s grpc.ServiceRegistrar, srv ExchangeAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedExchangeAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeAdminService_ServiceDesc, srv)
}

func _ExchangeAdminService_ListPlaceholderCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlaceholderCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeAdminServiceServer).ListPlaceholderCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeAdminService_ListPlaceholderCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeAdminServiceServer).ListPlaceholderCurrencies(ctx, req.(*ListPlaceholderCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeAdminService_CurateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeAdminServiceServer).CurateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeAdminService_CurateCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeAdminServiceServer).CurateCurrency(ctx, req.(*CurateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeAdminService_SyncCurrenciesFromScout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncCurrenciesFromScoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeAdminServiceServer).SyncCurrenciesFromScout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeAdminService_SyncCurrenciesFromScout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeAdminServiceServer).SyncCurrenciesFromScout(ctx, req.(*SyncCurrenciesFromScoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeAdminService_BootstrapDefaultRatePairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapDefaultRatePairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeAdminServiceServer).BootstrapDefaultRatePairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeAdminService_BootstrapDefaultRatePairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeAdminServiceServer).BootstrapDefaultRatePairs(ctx, req.(*BootstrapDefaultRatePairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeAdminService_ServiceDesc is the grpc.ServiceDesc for ExchangeAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.v1.ExchangeAdminService",
	HandlerType: (*ExchangeAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlaceholderCurrencies",
			Handler:    _ExchangeAdminService_ListPlaceholderCurrencies_Handler,
		},
		{
			MethodName: "CurateCurrency",
			Handler:    _ExchangeAdminService_CurateCurrency_Handler,
		},
		{
			MethodName: "SyncCurrenciesFromScout",
			Handler:    _ExchangeAdminService_SyncCurrenciesFromScout_Handler,
		},
		{
			MethodName: "BootstrapDefaultRatePairs",
			Handler:    _ExchangeAdminService_BootstrapDefaultRatePairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange/v1/admin.proto",
}
