// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: exchange/v1/query.proto

package exchangev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateView int32

const (
	RateView_RATE_VIEW_UNSPECIFIED RateView = 0
	RateView_RATE_VIEW_VOLUME      RateView = 1
	RateView_RATE_VIEW_PRICE       RateView = 2
)

// Enum value maps for RateView.
var (
	RateView_name = map[int32]string{
		0: "RATE_VIEW_UNSPECIFIED",
		1: "RATE_VIEW_VOLUME",
		2: "RATE_VIEW_PRICE",
	}
	RateView_value = map[string]int32{
		"RATE_VIEW_UNSPECIFIED": 0,
		"RATE_VIEW_VOLUME":      1,
		"RATE_VIEW_PRICE":       2,
	}
)

func (x RateView) Enum() *RateView {
	p := new(RateView)
	*p = x
	return p
}

func (x RateView) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateView) Descriptor() protoreflect.EnumDescriptor {
	return file_exchange_v1_query_proto_enumTypes[0].Descriptor()
}

func (RateView) Type() protoreflect.EnumType {
	return &file_exchange_v1_query_proto_enumTypes[0]
}

func (x RateView) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateView.Descriptor instead.
func (RateView) EnumDescriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{0}
}

type CurrencyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemPath      string                 `protobuf:"bytes,1,opt,name=item_path,json=itemPath,proto3" json:"item_path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TradeId       string                 `protobuf:"bytes,3,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyRef) Reset() {
	*x = CurrencyRef{}
	mi := &file_exchange_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyRef) ProtoMessage() {}

func (x *CurrencyRef) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyRef.ProtoReflect.Descriptor instead.
func (*CurrencyRef) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *CurrencyRef) GetItemPath() string {
	if x != nil {
		return x.ItemPath
	}
	return ""
}

func (x *CurrencyRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrencyRef) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	League        string                 `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	View          RateView               `protobuf:"varint,2,opt,name=view,proto3,enum=exchange.v1.RateView" json:"view,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_exchange_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesRequest) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

func (x *GetRatesRequest) GetView() RateView {
	if x != nil {
		return x.View
	}
	return RateView_RATE_VIEW_UNSPECIFIED
}

func (x *GetRatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RankedRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *CurrencyRef           `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Vwap          float64                `protobuf:"fixed64,2,opt,name=vwap,proto3" json:"vwap,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	BaseVolume    uint64                 `protobuf:"varint,5,opt,name=base_volume,json=baseVolume,proto3" json:"base_volume,omitempty"`
	QuoteVolume   uint64                 `protobuf:"varint,6,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"`
	Via           *CurrencyRef           `protobuf:"bytes,7,opt,name=via,proto3" json:"via,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedRate) Reset() {
	*x = RankedRate{}
	mi := &file_exchange_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedRate) ProtoMessage() {}

func (x *RankedRate) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedRate.ProtoReflect.Descriptor instead.
func (*RankedRate) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *RankedRate) GetCurrency() *CurrencyRef {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *RankedRate) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *RankedRate) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *RankedRate) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *RankedRate) GetBaseVolume() uint64 {
	if x != nil {
		return x.BaseVolume
	}
	return 0
}

func (x *RankedRate) GetQuoteVolume() uint64 {
	if x != nil {
		return x.QuoteVolume
	}
	return 0
}

func (x *RankedRate) GetVia() *CurrencyRef {
	if x != nil {
		return x.Via
	}
	return nil
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CurrencyRef           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Rates         []*RankedRate          `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty"`
	HourUtc       int64                  `protobuf:"varint,3,opt,name=hour_utc,json=hourUtc,proto3" json:"hour_utc,omitempty"`
	League        string                 `protobuf:"bytes,4,opt,name=league,proto3" json:"league,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_exchange_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetRatesResponse) GetBase() *CurrencyRef {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetRatesResponse) GetRates() []*RankedRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *GetRatesResponse) GetHourUtc() int64 {
	if x != nil {
		return x.HourUtc
	}
	return 0
}

func (x *GetRatesResponse) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

type ListLeaguesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HourUtc       int64                  `protobuf:"varint,1,opt,name=hour_utc,json=hourUtc,proto3" json:"hour_utc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaguesRequest) Reset() {
	*x = ListLeaguesRequest{}
	mi := &file_exchange_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaguesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaguesRequest) ProtoMessage() {}

func (x *ListLeaguesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaguesRequest.ProtoReflect.Descriptor instead.
func (*ListLeaguesRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *ListLeaguesRequest) GetHourUtc() int64 {
	if x != nil {
		return x.HourUtc
	}
	return 0
}

type ListLeaguesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leagues       []string               `protobuf:"bytes,1,rep,name=leagues,proto3" json:"leagues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaguesResponse) Reset() {
	*x = ListLeaguesResponse{}
	mi := &file_exchange_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaguesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaguesResponse) ProtoMessage() {}

func (x *ListLeaguesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaguesResponse.ProtoReflect.Descriptor instead.
func (*ListLeaguesResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *ListLeaguesResponse) GetLeagues() []string {
	if x != nil {
		return x.Leagues
	}
	return nil
}

type ListDefaultRatePairsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefaultRatePairsRequest) Reset() {
	*x = ListDefaultRatePairsRequest{}
	mi := &file_exchange_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefaultRatePairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefaultRatePairsRequest) ProtoMessage() {}

func (x *ListDefaultRatePairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefaultRatePairsRequest.ProtoReflect.Descriptor instead.
func (*ListDefaultRatePairsRequest) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{6}
}

type DefaultRatePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *CurrencyRef           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote         *CurrencyRef           `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultRatePair) Reset() {
	*x = DefaultRatePair{}
	mi := &file_exchange_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultRatePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRatePair) ProtoMessage() {}

func (x *DefaultRatePair) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRatePair.ProtoReflect.Descriptor instead.
func (*DefaultRatePair) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *DefaultRatePair) GetBase() *CurrencyRef {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DefaultRatePair) GetQuote() *CurrencyRef {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *DefaultRatePair) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListDefaultRatePairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*DefaultRatePair     `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefaultRatePairsResponse) Reset() {
	*x = ListDefaultRatePairsResponse{}
	mi := &file_exchange_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefaultRatePairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefaultRatePairsResponse) ProtoMessage() {}

func (x *ListDefaultRatePairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefaultRatePairsResponse.ProtoReflect.Descriptor instead.
func (*ListDefaultRatePairsResponse) Descriptor() ([]byte, []int) {
	return file_exchange_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *ListDefaultRatePairsResponse) GetPairs() []*DefaultRatePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

var File_exchange_v1_query_proto protoreflect.FileDescriptor

const file_exchange_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x17exchange/v1/query.proto\x12\vexchange.v1\x1a\x1cgoogle/api/annotations.proto\"Y\n" +
	"\vCurrencyRef\x12\x1b\n" +
	"\titem_path\x18\x01 \x01(\tR\bitemPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\btrade_id\x18\x03 \x01(\tR\atradeId\"j\n" +
	"\x0fGetRatesRequest\x12\x16\n" +
	"\x06league\x18\x01 \x01(\tR\x06league\x12)\n" +
	"\x04view\x18\x02 \x01(\x0e2\x15.exchange.v1.RateViewR\x04view\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xec\x01\n" +
	"\n" +
	"RankedRate\x124\n" +
	"\bcurrency\x18\x01 \x01(\v2\x18.exchange.v1.CurrencyRefR\bcurrency\x12\x12\n" +
	"\x04vwap\x18\x02 \x01(\x01R\x04vwap\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x01R\x03low\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x1f\n" +
	"\vbase_volume\x18\x05 \x01(\x04R\n" +
	"baseVolume\x12!\n" +
	"\fquote_volume\x18\x06 \x01(\x04R\vquoteVolume\x12*\n" +
	"\x03via\x18\a \x01(\v2\x18.exchange.v1.CurrencyRefR\x03via\"\xa2\x01\n" +
	"\x10GetRatesResponse\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.exchange.v1.CurrencyRefR\x04base\x12-\n" +
	"\x05rates\x18\x02 \x03(\v2\x17.exchange.v1.RankedRateR\x05rates\x12\x19\n" +
	"\bhour_utc\x18\x03 \x01(\x03R\ahourUtc\x12\x16\n" +
	"\x06league\x18\x04 \x01(\tR\x06league\"/\n" +
	"\x12ListLeaguesRequest\x12\x19\n" +
	"\bhour_utc\x18\x01 \x01(\x03R\ahourUtc\"/\n" +
	"\x13ListLeaguesResponse\x12\x18\n" +
	"\aleagues\x18\x01 \x03(\tR\aleagues\"\x1d\n" +
	"\x1bListDefaultRatePairsRequest\"\x8e\x01\n" +
	"\x0fDefaultRatePair\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.exchange.v1.CurrencyRefR\x04base\x12.\n" +
	"\x05quote\x18\x02 \x01(\v2\x18.exchange.v1.CurrencyRefR\x05quote\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"R\n" +
	"\x1cListDefaultRatePairsResponse\x122\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1c.exchange.v1.DefaultRatePairR\x05pairs*P\n" +
	"\bRateView\x12\x19\n" +
	"\x15RATE_VIEW_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RATE_VIEW_VOLUME\x10\x01\x12\x13\n" +
	"\x0fRATE_VIEW_PRICE\x10\x022\xe7\x02\n" +
	"\x14ExchangeQueryService\x12Z\n" +
	"\bGetRates\x12\x1c.exchange.v1.GetRatesRequest\x1a\x1d.exchange.v1.GetRatesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/rates\x12e\n" +
	"\vListLeagues\x12\x1f.exchange.v1.ListLeaguesRequest\x1a .exchange.v1.ListLeaguesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/leagues\x12\x8b\x01\n" +
	"\x14ListDefaultRatePairs\x12(.exchange.v1.ListDefaultRatePairsRequest\x1a).exchange.v1.ListDefaultRatePairsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/rate-pairs/defaultBFZDgithub.com/grysha11/poe-tg-tracker/internal/pb/exchangev1;exchangev1b\x06proto3"

var (
	file_exchange_v1_query_proto_rawDescOnce sync.Once
	file_exchange_v1_query_proto_rawDescData []byte
)

func file_exchange_v1_query_proto_rawDescGZIP() []byte {
	file_exchange_v1_query_proto_rawDescOnce.Do(func() {
		file_exchange_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exchange_v1_query_proto_rawDesc), len(file_exchange_v1_query_proto_rawDesc)))
	})
	return file_exchange_v1_query_proto_rawDescData
}

var file_exchange_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_exchange_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_exchange_v1_query_proto_goTypes = []any{
	(RateView)(0),                        // 0: exchange.v1.RateView
	(*CurrencyRef)(nil),                  // 1: exchange.v1.CurrencyRef
	(*GetRatesRequest)(nil),              // 2: exchange.v1.GetRatesRequest
	(*RankedRate)(nil),                   // 3: exchange.v1.RankedRate
	(*GetRatesResponse)(nil),             // 4: exchange.v1.GetRatesResponse
	(*ListLeaguesRequest)(nil),           // 5: exchange.v1.ListLeaguesRequest
	(*ListLeaguesResponse)(nil),          // 6: exchange.v1.ListLeaguesResponse
	(*ListDefaultRatePairsRequest)(nil),  // 7: exchange.v1.ListDefaultRatePairsRequest
	(*DefaultRatePair)(nil),              // 8: exchange.v1.DefaultRatePair
	(*ListDefaultRatePairsResponse)(nil), // 9: exchange.v1.ListDefaultRatePairsResponse
}
var file_exchange_v1_query_proto_depIdxs = []int32{
	0,  // 0: exchange.v1.GetRatesRequest.view:type_name -> exchange.v1.RateView
	1,  // 1: exchange.v1.RankedRate.currency:type_name -> exchange.v1.CurrencyRef
	1,  // 2: exchange.v1.RankedRate.via:type_name -> exchange.v1.CurrencyRef
	1,  // 3: exchange.v1.GetRatesResponse.base:type_name -> exchange.v1.CurrencyRef
	3,  // 4: exchange.v1.GetRatesResponse.rates:type_name -> exchange.v1.RankedRate
	1,  // 5: exchange.v1.DefaultRatePair.base:type_name -> exchange.v1.CurrencyRef
	1,  // 6: exchange.v1.DefaultRatePair.quote:type_name -> exchange.v1.CurrencyRef
	8,  // 7: exchange.v1.ListDefaultRatePairsResponse.pairs:type_name -> exchange.v1.DefaultRatePair
	2,  // 8: exchange.v1.ExchangeQueryService.GetRates:input_type -> exchange.v1.GetRatesRequest
	5,  // 9: exchange.v1.ExchangeQueryService.ListLeagues:input_type -> exchange.v1.ListLeaguesRequest
	7,  // 10: exchange.v1.ExchangeQueryService.ListDefaultRatePairs:input_type -> exchange.v1.ListDefaultRatePairsRequest
	4,  // 11: exchange.v1.ExchangeQueryService.GetRates:output_type -> exchange.v1.GetRatesResponse
	6,  // 12: exchange.v1.ExchangeQueryService.ListLeagues:output_type -> exchange.v1.ListLeaguesResponse
	9,  // 13: exchange.v1.ExchangeQueryService.ListDefaultRatePairs:output_type -> exchange.v1.ListDefaultRatePairsResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_exchange_v1_query_proto_init() }
func file_exchange_v1_query_proto_init() {
	if File_exchange_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exchange_v1_query_proto_rawDesc), len(file_exchange_v1_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_v1_query_proto_goTypes,
		DependencyIndexes: file_exchange_v1_query_proto_depIdxs,
		EnumInfos:         file_exchange_v1_query_proto_enumTypes,
		MessageInfos:      file_exchange_v1_query_proto_msgTypes,
	}.Build()
	File_exchange_v1_query_proto = out.File
	file_exchange_v1_query_proto_goTypes = nil
	file_exchange_v1_query_proto_depIdxs = nil
}
