// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: exchange/v1/query.proto

package exchangev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeQueryService_GetRates_FullMethodName             = "/exchange.v1.ExchangeQueryService/GetRates"
	ExchangeQueryService_ListLeagues_FullMethodName          = "/exchange.v1.ExchangeQueryService/ListLeagues"
	ExchangeQueryService_ListDefaultRatePairs_FullMethodName = "/exchange.v1.ExchangeQueryService/ListDefaultRatePairs"
)

// ExchangeQueryServiceClient is the client API for ExchangeQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeQueryServiceClient interface {
	GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error)
	ListLeagues(ctx context.Context, in *ListLeaguesRequest, opts ...grpc.CallOption) (*ListLeaguesResponse, error)
	ListDefaultRatePairs(ctx context.Context, in *ListDefaultRatePairsRequest, opts ...grpc.CallOption) (*ListDefaultRatePairsResponse, error)
}

type exchangeQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeQueryServiceClient(cc grpc.ClientConnInterface) ExchangeQueryServiceClient {
	return &exchangeQueryServiceClient{cc}
}

func (c *exchangeQueryServiceClient) GetRates(ctx context.Context, in *GetRatesRequest, opts ...grpc.CallOption) (*GetRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatesResponse)
	err := c.cc.Invoke(ctx, ExchangeQueryService_GetRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeQueryServiceClient) ListLeagues(ctx context.Context, in *ListLeaguesRequest, opts ...grpc.CallOption) (*ListLeaguesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaguesResponse)
	err := c.cc.Invoke(ctx, ExchangeQueryService_ListLeagues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeQueryServiceClient) ListDefaultRatePairs(ctx context.Context, in *ListDefaultRatePairsRequest, opts ...grpc.CallOption) (*ListDefaultRatePairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDefaultRatePairsResponse)
	err := c.cc.Invoke(ctx, ExchangeQueryService_ListDefaultRatePairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeQueryServiceServer is the server API for ExchangeQueryService service.
// All implementations must embed UnimplementedExchangeQueryServiceServer
// for forward compatibility.
type ExchangeQueryServiceServer interface {
	GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error)
	ListLeagues(context.Context, *ListLeaguesRequest) (*ListLeaguesResponse, error)
	ListDefaultRatePairs(context.Context, *ListDefaultRatePairsRequest) (*ListDefaultRatePairsResponse, error)
	mustEmbedUnimplementedExchangeQueryServiceServer()
}

// UnimplementedExchangeQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeQueryServiceServer struct{}

func (UnimplementedExchangeQueryServiceServer) GetRates(context.Context, *GetRatesRequest) (*GetRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRates not implemented")
}
func (UnimplementedExchangeQueryServiceServer) ListLeagues(context.Context, *ListLeaguesRequest) (*ListLeaguesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeagues not implemented")
}
func (UnimplementedExchangeQueryServiceServer) ListDefaultRatePairs(context.Context, *ListDefaultRatePairsRequest) (*ListDefaultRatePairsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDefaultRatePairs not implemented")
}
func (UnimplementedExchangeQueryServiceServer) mustEmbedUnimplementedExchangeQueryServiceServer() {}
func (UnimplementedExchangeQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeExchangeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeQueryServiceServer will
// result in compilation errors.
type UnsafeExchangeQueryServiceServer interface {
	mustEmbedUnimplementedExchangeQueryServiceServer()
}

func RegisterExchangeQueryServiceServer(s grpc.ServiceRegistrar, srv ExchangeQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedExchangeQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeQueryService_ServiceDesc, srv)
}

func _ExchangeQueryService_GetRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeQueryServiceServer).GetRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeQueryService_GetRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeQueryServiceServer).GetRates(ctx, req.(*GetRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeQueryService_ListLeagues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeQueryServiceServer).ListLeagues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeQueryService_ListLeagues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeQueryServiceServer).ListLeagues(ctx, req.(*ListLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeQueryService_ListDefaultRatePairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDefaultRatePairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeQueryServiceServer).ListDefaultRatePairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeQueryService_ListDefaultRatePairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeQueryServiceServer).ListDefaultRatePairs(ctx, req.(*ListDefaultRatePairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeQueryService_ServiceDesc is the grpc.ServiceDesc for ExchangeQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.v1.ExchangeQueryService",
	HandlerType: (*ExchangeQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRates",
			Handler:    _ExchangeQueryService_GetRates_Handler,
		},
		{
			MethodName: "ListLeagues",
			Handler:    _ExchangeQueryService_ListLeagues_Handler,
		},
		{
			MethodName: "ListDefaultRatePairs",
			Handler:    _ExchangeQueryService_ListDefaultRatePairs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange/v1/query.proto",
}
