image:
  repository: ghcr.io/grysha11/poe-tg-tracker
  tag: 62e659ac0c6a23db10f5ec32137066735f9f58ae
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-pull
existingSecret: poe-tracker-secrets
config:
  POE_LEAGUE: "Forbidden Rites"
  POE_CONTACT: "contact: zakharchenkoevhenii@gmail.com"
  LOG_LEVEL: "info"
migrate:
  enabled: true
  activeDeadlineSeconds: 600
fetchCron:
  schedule: "1 * * * *"
  backoffLimit: 3
vtgate:
  serviceName: vtgate
  externalName: vitess-homelab-vtgate-43f81d05.vitess.svc.cluster.local
mysql:
  enabled: false
sealedSecrets:
  enabled: true
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
readinessProbe:
  enabled: false
  path: /healthz
  port: 8080
