image:
  repository: ghcr.io/grysha11/poe-tg-tracker
  tag: ce52d34f0e2aae8df53872de4769125e9253912b
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-pull
existingSecret: poe-tracker-secrets
config:
  POE_LEAGUE: "Forbidden Rites"
  POE_CONTACT: "contact: zakharchenkoevhenii@gmail.com"
  LOG_LEVEL: "info"
fetchCron:
  schedule: "1 * * * *"
  backoffLimit: 3
vtgate:
  serviceName: vtgate
  externalName: vitess-homelab-vtgate-43f81d05.vitess.svc.cluster.local
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi
readinessProbe:
  enabled: false
  path: /healthz
  port: 8080
